const navigationPath = {
  CREATE_JOB_STACK: 'CreateJobStack',
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  LOGIN: 'Login',
  SERVICES: 'Services',
  CUSTOMER_LOGIN: 'CustomerLogin',
  CUSTOMER_SIGNUP: 'CustomerSignUp',
  CUSTOMER_JOB_DETAILS: 'CustomerJobDetails',
  OTP_VERIFICATION_EMAIL: 'OtpVerificationEmail',
  FIELD_WORKER_LOGIN: 'FieldWorkerLogin',
  FIELD_WORKER_SIGNUP: 'FieldWorkerSignUp',
  DETAILS: 'Details',
  CALENDAR: 'Calendar',
  CATEGORIES: 'Categories',
  CREATE_JOB: 'CreateJob',
  JOB_DETAILS: 'JobDetails',
  APPOINTMENT: 'Appointment',
  APPOINTMENT_CALENDAR: 'AppointmentCalendar',
  APPOINTMENT_DETAILS: 'AppointmentDetails',
  DASHBOARD: 'Dashboard',
  WAITING_PAGES: 'WaitingPages',
  HOME: 'Home',
  EVENT: 'Event',
  PROFILE: 'Profile',
  OTP_VERIFICATION: 'OtpVerification',
  SIGNUP_OTP_VERIFICATION: 'signUpOtpVerification',
  PAGE_VIEW: 'PageView',
  POINT_CHECK_LIST: 'PointCheckList',
  UPLOAD_PHOTOS: 'UploadPhotos',
};
export default navigationPath;
